import type { AstroIntegration } from 'astro';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import { basename, join, resolve } from 'node:path';
import { remarkWikilinks } from './lib/remark-wikilinks.js';

export interface GraphGardenConfig {
  /** Path to the markdown vault directory (relative to project root) */
  vault: string;
  /** Site title shown in the header */
  title?: string;
  /** Additional Shiki languages for syntax highlighting */
  langs?: any[];
}

export default function graphGarden(config: GraphGardenConfig): AstroIntegration {
  const { vault, title = 'Knowledge', langs = [] } = config;

  const pkgDir = new URL('./', import.meta.url);
  const almideGrammar = JSON.parse(
    readFileSync(fileURLToPath(new URL('grammars/almide.tmLanguage.json', pkgDir)), 'utf-8')
  );

  return {
    name: '@o6lvl4/graph-garden',
    hooks: {
      'astro:config:setup': ({ updateConfig, injectRoute, config: astroConfig, command }) => {
        // Auto-generate vault index.md
        if (command === 'build' || command === 'dev') {
          generateVaultIndex(resolve(vault), title);
        }

        // Copy default favicon if user doesn't have one
        if (command === 'build' || command === 'dev') {
          const publicDir = fileURLToPath(astroConfig.publicDir);
          const faviconDest = resolve(publicDir, 'favicon.svg');
          if (!existsSync(faviconDest)) {
            mkdirSync(publicDir, { recursive: true });
            copyFileSync(
              fileURLToPath(new URL('../assets/favicon.svg', pkgDir)),
              faviconDest
            );
          }
        }
        const base = astroConfig.base || '/';

        updateConfig({
          markdown: {
            remarkPlugins: [[remarkWikilinks, { base }]],
            shikiConfig: {
              theme: 'github-dark',
              langs: [{ ...almideGrammar, aliases: ['almd'] }, ...langs],
            },
          },
          vite: {
            plugins: [
              {
                name: 'graph-garden-virtual',
                resolveId(id: string) {
                  if (id === 'virtual:graph-garden/config') return '\0virtual:graph-garden/config';
                },
                load(id: string) {
                  if (id === '\0virtual:graph-garden/config') {
                    return `export const title = ${JSON.stringify(title)};`;
                  }
                },
              },
            ],
          },
        });

        // Inject routes from package
        const pagesDir = new URL('pages/', pkgDir);
        const r = (file: string) => fileURLToPath(new URL(file, pagesDir));

        injectRoute({ pattern: '/', entrypoint: r('index.astro') });
        injectRoute({ pattern: '/graph', entrypoint: r('graph.astro') });
        injectRoute({ pattern: '/tags', entrypoint: r('tags/index.astro') });
        injectRoute({ pattern: '/tags/[tag]', entrypoint: r('tags/[tag].astro') });
        injectRoute({ pattern: '/notes/[...slug]', entrypoint: r('notes/[...slug].astro') });
        injectRoute({ pattern: '/search-index.json', entrypoint: r('search-index.json.ts') });
        injectRoute({ pattern: '/graph-data.json', entrypoint: r('graph-data.json.ts') });
      },
    },
  };
}

function generateVaultIndex(vaultDir: string, siteTitle: string) {
  const indexPath = join(vaultDir, 'index.md');

  // Collect all notes (excluding index.md)
  const files = findMarkdownFiles(vaultDir).filter((f) => basename(f) !== 'index.md');

  interface NoteInfo {
    name: string;
    title: string;
    tags: string[];
    isPublic: boolean;
  }

  const notes: NoteInfo[] = files.map((filePath) => {
    const content = readFileSync(filePath, 'utf-8');
    const name = basename(filePath, '.md');
    const fm = parseFrontmatter(content);
    return {
      name,
      title: fm.title || name,
      tags: fm.tags || [],
      isPublic: fm.public !== false,
    };
  });

  const publicNotes = notes.filter((n) => n.isPublic);

  // Group by first tag
  const grouped = new Map<string, NoteInfo[]>();
  for (const note of publicNotes) {
    const group = note.tags[0] || 'other';
    if (!grouped.has(group)) grouped.set(group, []);
    grouped.get(group)!.push(note);
  }

  // Generate markdown
  const lines = [
    '---',
    'title: Welcome',
    'tags: [meta]',
    '---',
    '',
    `<!-- auto-generated by graph-garden -->`,
    '',
    `${siteTitle} の knowledge base。`,
    '',
    '## Notes',
    '',
  ];

  for (const [tag, tagNotes] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`### ${tag}`);
    lines.push('');
    for (const note of tagNotes.sort((a, b) => a.title.localeCompare(b.title))) {
      lines.push(`- [[${note.name}]] - ${note.title}`);
    }
    lines.push('');
  }

  writeFileSync(indexPath, lines.join('\n'));
}

function findMarkdownFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    if (entry.name === 'attachments') continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findMarkdownFiles(full));
    } else if (entry.name.endsWith('.md')) {
      results.push(full);
    }
  }
  return results;
}

function parseFrontmatter(content: string): Record<string, any> {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fm: Record<string, any> = {};
  for (const line of match[1].split('\n')) {
    const m = line.match(/^(\w+):\s*(.+)$/);
    if (!m) continue;
    const [, key, val] = m;
    if (val === 'true') fm[key] = true;
    else if (val === 'false') fm[key] = false;
    else if (val.startsWith('[')) {
      fm[key] = val.slice(1, -1).split(',').map((s) => s.trim());
    } else {
      fm[key] = val;
    }
  }
  return fm;
}

// Re-export utilities
export { slugify } from './lib/slugify.js';
export { extractWikilinks, buildGraphData } from './lib/graph.js';
export { remarkWikilinks } from './lib/remark-wikilinks.js';
